apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-app
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{- with secret "internal/data/database/config" -}}
             export MYSQL_ROOT_PASSWORD={{ .Data.data.password }}
          {{- end -}}
      labels:
        app: mysql-app
    spec:
      serviceAccountName: internal-app
      containers:
        - name: mysql-container
          image: mysql
          command: ["/bin/sh", "-c"]
          args:
            ["source /vault/secrets/database-config && docker-entrypoint.sh"]
          env:
            - name: MYSQL_DATABASE
              value: test-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
