apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root #TODO: password in secrets
            - name: MYSQL_DATABASE
              value: test-db
            - name: MYSQL_USER
              value: root
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
