apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "internal/data/database/config" -}}
            export DB_PASSWORD="{{ .Data.data.password }}" DB_USERNAME="{{ .Data.data.username }}"
          {{- end -}}
      labels:
        app: books-api
    spec:
      serviceAccountName: internal-app
      containers:
        - name: books-api
          image: mmmarzouki/example-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: 10.96.43.169
            - name: DB_NAME
              value: test-db
            - name: DB_DIALECT
              value: mysql
