apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{- with secret "internal/data/database/config" -}}
            export DB_PASSWORD={{ .Data.data.password }} DB_USER={{ .Data.data.username }}
          {{- end -}}
      labels:
        app: books-api
    spec:
      serviceAccountName: internal-app
      containers:
        - name: books-api
          image: mmmarzouki/example-app:latest
          command: ["/bin/sh", “-c”]
          args:
            [
              "source /vault/secrets/database-config && env >> /home/node/vars && sleep 10",
            ]
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: 10.103.196.189
            - name: DB_NAME
              value: test-db
            - name: DB_DIALECT
              value: mysql
